### ISSUE TITLE
converge-ui needs to be replaced by new ui-alchemy

### ISSUE THREAD

**Issue by eggmaster** [aeolusproject/conductor#209]
`git submodule init` and `git submodule update` no longer work with a fresh clone of conductor because upstream is undergoing a project name change. This needs to be addressed in the conductor rpm spec as well as whatever is pointing the submodule config at the old converge-ui

**Comment by jcoufal** [comment]
It should work, because we kept the old repository at the same place 
(under Katello org). Anyway the movement to the new alchemy repo is 
under process right now. But thanks for the notice. We are trying to 
create a gem from the alchemy and replace submodules in the future...

On 30.11.2012 21:27, Steve Linabery wrote:

> |git submodule init| and |git submodule update| no longer work with a 
> fresh clone of conductor because upstream is undergoing a project name 
> change. This needs to be addressed in the conductor rpm spec as well 
> as whatever is pointing the submodule config at the old converge-ui
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/aeolusproject/conductor/issues/209.

## 

Jaromír Coufal

Interaction Designer
Red Hat Czech s.r.o.

Mobile: +420 724 595 508
E-mail: jcoufal@redhat.com
IRC: jcoufal at #cloudforms-ui, #aeolus, #brno

**Comment by eggmaster** [comment]
Can anyone else replicate my error of being unable to set up the submodule with a fresh clone of the conductor repo? TIA.

**Comment by jcoufal** [comment]
I just did fresh new clone with "submodule update -i" (= init and then update) and it works correctly.

**Comment by bmclaughlin** [comment]
I ran into potentially the same issue late last week where on a fresh F16 install I could not get the converge-ui-devel dependency required for building Conductor from source as there are no tags in the converge-ui repo for tito to pick up.  I needed to generate the rpm from the new Alchemy repo instead, it wasn't an optimal user experience...

I had no issue with git submodule init/update.

**Comment by eggmaster** [comment]
That's right. Sorry, I misread the output of the script I use to set up my local repo. bmclaughlin is correct; the problem is with `tito build --test --rpm`

I am closing this issue and opening one with the real error.
