### ISSUE TITLE
Hardware profile - test for name uniqueness

### ISSUE THREAD

**Issue by jcoufal** [aeolusproject/conductor#396]
Currently we test uniqueness of the HWP Name against provider, which doesn't make sense.

HWPs are created as frontend HWPs in Conductor not depending on any provider, so we shouldn't check uniqueness of their names against Provider ID.

Needs to be fixed in form's hints as well, see #263.

**Comment by ifarkas** [comment]
As it turned out, there are 2 types of Hardware Profiles: backend and frontend ones. In Conductor both of them are represented by the same class. The only difference between them is that there is no Provider associated with fronted Hardware Profiles. 

Therefore, the validation is correct but since in the UI we are only dealing with fronted Hardware Profiles I will modify the hint message for the name in the original pull request.

Closing this one.
